In [1]:
import os
import pandas as pd

In [4]:
directory = 'H:\내 드라이브\datasets\original_crawling'
filenames = os.listdir(directory)
filenames = filenames[:-1]

In [14]:
metadata = pd.DataFrame()

for file in filenames:
    temp = pd.read_csv(file, index_col=False)
    temp.drop('Unnamed: 0', axis=1, inplace=True)
    metadata= pd.concat([metadata, temp], ignore_index=True)

In [21]:
metadata[metadata.duplicated(['Title', 'Artist'], keep=False)]

       Genre              Title     Artist
4     Ballad                 인사         범진
14    Ballad            사랑할 수밖에     볼빨간사춘기
15    Ballad  그대가 내 안에 박혔다(그내박)    순순희(기태)
20    Ballad          해요 (2022)        #안녕
44    Ballad                 선물       멜로망스
...      ...                ...        ...
2099  Hiphop      Downtown Baby  블루 (BLOO)
2116  Hiphop               입장차이         오반
2119  Hiphop               새벽에만         도규
2151  Hiphop              쿠키 영상         오반
2194  Hiphop    다시 보고 싶은 영화가 있어  영화 (mu.b)

[268 rows x 3 columns]

In [33]:
metadata_unique = metadata.drop_duplicates(['Title', 'Artist'])
metadata_unique = metadata_unique.reset_index(drop=True)
metadata_unique['Id'] = metadata_unique.index
metadata_unique = metadata_unique[['Id', 'Title', 'Artist', 'Genre']]

In [35]:
metadata_unique.to_csv('H:\\내 드라이브\\datasets\\metadata.csv', index=False)

In [34]:
metadata_unique

,Id,Title,Artist,Genre
0,0,Love wins all,아이유,Ballad
1,1,비의 랩소디,임재현,Ballad
2,2,그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection)),너드커넥션 (Nerd Connection),Ballad
3,3,헤어지자 말해요,박재정,Ballad
4,4,인사,범진,Ballad
...,...,...,...,...
2071,2071,Life Goes On,방탄소년단,Hiphop
2072,2072,Catch (Feat. 화사),에픽하이 (EPIK HIGH),Hiphop
2073,2073,CASE 143,Stray Kids (스트레이 키즈),Hiphop
2074,2074,WE (Feat. 박재범) (Prod. by Slom),XINSAYNE,Hiphop
2075,2075,DJ,NCT 127,Hiphop